export const workExperienceData = {
  titleWorkExp: [
    "Données d'expériences professionnelles",
    "Work experiences datas",
  ],
  titleEducExp: ["Données de scolarité", "Education datas"],
  keyword: {
    name: ["nom: ", "name: "],
    location: ["lieu: ", "location: "],
    modal: {
      usualActivity: ["Mes tâches au quotidien", "My usual tasks"],
      usefulInformations: ["Informations pratiques", "Useful Informations"],
      tel: ["Tél: ", "Phone: "],
      adress: ["Adresse: ", "Adress: "],
      webSite: ["Site web: ", "WebSite: "],
    },
  },
  animator: {
    comment: [
      "//Experience pro en tant qu'animateur en cybercentre",
      "//Work experience as cybercentre animator",
    ],
    job: ["Animateur en  cybercentre", "Cybercenter animator"],
    name: "‘L'Archy'Made’",
    location: "‘Champigné 49300’",
    date: ["‘Février 2017 - Mai 2021’", "‘Febuary 2017 - May 2021’"],
    infos: {
      name: "L'Archy'Made",
      job: ["Animateur en  cybercentre", "Cybercenter animator"],
      description: [
        "Le Cybercentre du Haut-Anjou, était situé à Champigné. Nous étions un lieu d'accueil ouvert à tous les habitants qui souhaitaient obtenir une initiation aux nouvelles technologies. Il permet d’acquérir des connaissances en informatique par le biais d’ateliers d’initiation. L'association a dût fermer suite aux évènements liés au covid",
        "The Haut-Anjou Cybercentre was located at Champigné. We were a welcoming place open to all residents who wanted to get an introduction to new technologies. It made it possible to acquire computer knowledge through introductory workshops. The association had to close because of events related to covid",
      ],
      logo: "archy",
      activityFr: [
        "Accueil clientèle",
        "Ateliers d'initiation",
        "Interventions scolaire",
        "Assistance numérique",
      ],
      activityEn: [
        "Customer reception",
        "Initiation workshops",
        "School interventions",
        "Digital assistance",
      ],
      tel: "",
      mail: "",
      location: "Les Hauts d'anjou 49330",
      web: "https://leshautsdanjou.fr",
    },
  },
  hotlinerOrange: {
    comment: [
      "//Experience pro en tant que hotliner",
      "//Work experience as hotliner",
    ],
    job: "Hotliner",
    name: ["‘Stream(Orange)’"],
    location: "‘Angers 49000’",
    date: ["‘Novembre 2015 - Février 2017’", "‘November 2015 - Febuary 2017’"],
    infos: {
      name: "Stream(Orange)",
      job: ["Hotliner", "Hotliner"],
      description: [
        "Stream Global Services, était une société BPO acquise par Convergys suite à une fusion définitive, avec plus de 37,000 employés dans 22 pays et 50 centres d'appels. La société est présente en Amérique du Nord, Europe, Asie-pacifique, Amérique Latine, Moyen-Orien et Afrique.",
        "Stream Global Services, was a BPO company acquired by Convergys through a definitive merger, together with more than 37,000 employees in 22 countries and 50 contact centers. The footprint of the company included countries across North America, Europe, Asia Pacific, Latin America, Middle East and Africa.",
      ],
      logo: "stream",
      activityFr: [
        "Accueil téléphonique",
        "Diagnostiquer un problème technique",
        "Apporter la solution la plus adéquat",
      ],
      activityEn: [
        "Telephone reception",
        "Diagnose a technical problem",
        "Provide the most appropriate solution",
      ],
      tel: "02 41 74 23 00",
      mail: "",
      location: "Angers 49000",
      web: "https://www.concentrix.com",
    },
  },
  gameDesign: {
    comment: [
      "//Experience pro en tant que game designer",
      "Work experience as game designer",
    ],
    job: ["Chef de projet - Game Designer", "Lead Produceur - Game Designer"],
    name: "‘Studio Nyx’",
    location: "‘Angoulême 16000’",
    date: ["‘Mars 2014 - Séptembre 2015’", "‘March 2014 - September 2015’"],
    infos: {
      name: "Studio Nyx",
      job: ["Chef de projet - Game Designer", "Lead producer - Game Designer"],
      description: [
        "Nyx est un studio de développement de jeux vidéo et de simulateurs en réalité virtuelle (VR) à Angoulême. Leur rôle est d'accompagner dans leur transition numérique les secteurs de la construction, de l'industrie, du tourisme et de la culture.",
        "Nyx is a development studio for video games and virtual reality (VR) simulators in Angoulême. They support the construction, industry, tourism and culture sectors in their digital transition.",
      ],
      logo: "studionyx",
      activityFr: [
        "Gestion d'une équipe de 5 membres",
        "Réalisation de Game Design",
        "Réalisation de Level Design",
        "Réalisation de cahier des charges",
        "Qa Test",
      ],
      activityEn: [
        "Management of a 5 members team",
        "Making Game Design",
        "Making Level Design",
        "Drafting of specifications",
        "Qa Test",
      ],
      tel: "02 41 74 23 00",
      mail: "jobs@studio-nyx.com",
      location: "Angoulême 16000",
      web: "https://www.studio-nyx.com",
    },
  },
  railways: {
    comment: [
      "//Experience pro en tant que poseur de voie ferrée",
      "//Work experience as setter railways",
    ],
    job: ["Poseur de voie ferrée", "Setter Railways"],
    name: "‘CLMTP’",
    location: "‘Sablé-sur-Sarthe  72300’",
    date: ["‘Août 2012 -  Décembre  2013’", "‘August 2012 - December 2013"],
    infos: {
      name: "CLMTP",
      job: ["Poseur de voie ferrée", "setter Railways"],
      description: [
        "Fondée en 1994 par Zéphir CLAISSE, le nom de l’entreprise CLMTP se marie avec passion et rigueur dans le domaine des travaux de voie ferrée. La vocation et le savoir-faire de quatre générations et de collaborateurs ont permis à la société CLMTP de se positionner comme une référence dans le milieu ferroviaire. ",
        "Founded in 1994 by Zéphir CLAISSE, the name of the CLMTP company is combined with passion and rigor in the field of railway works. The vocation and know-how of four generations and employees have enabled the CLMTP company to to position itself as a reference in the railway environment. ",
      ],
      logo: "clmtp",
      activityFr: [
        "Travail en déplacement dans toute la france 5J/7",
        "Maintenance des voies ferroviaires",
        "Respect des normes de sécurité",
      ],
      activityEn: [
        "Working on the move throughout France 5 days a week",
        "Maintenance of railway tracks",
        "Compliance with safety standards",
      ],
      tel: "02 43 95 43 73",
      mail: "contact@clmtp.fr",
      location: "Sablé-Sur-Sarthe 72300",
      web: "http://www.clmtp.fr",
    },
  },
  hotlinerCanal: {
    comment: [
      "//Experience pro en tant que hotliner",
      "//Work experience as hotliner",
    ],
    job: ["Hotliner"],
    name: ["‘Stream(Canal+)’"],
    location: "‘Angers 49000’",
    date: [
      "‘Septembre 2010 - Février 2011’",
      "‘September 2010 - Febuary 2011’",
    ],
    infos: {
      name: "Stream(Canal+)",
      job: ["Hotliner", "Hotliner"],
      description: [
        "Stream Global Services, était une société BPO acquise par Convergys suite à une fusion définitive, avec plus de 37,000 employés dans 22 pays et 50 centres d'appels. La société est présente en Amérique du Nord, Europe, Asie-pacifique, Amérique Latine, Moyen-Orien et Afrique.",
        "Stream Global Services, was a BPO company acquired by Convergys through a definitive merger, together with more than 37,000 employees in 22 countries and 50 contact centers. The footprint of the company included countries across North America, Europe, Asia Pacific, Latin America, Middle East and Africa.",
      ],
      logo: "stream",
      activityFr: [
        "Accueil téléphonique",
        "Diagnostiquer un problème technique",
        "Apporter la solution la plus adéquat",
      ],
      activityEn: [
        "Telephone reception",
        "Diagnose a technical problem",
        "Provide the most appropriate solution",
      ],
      tel: "02 41 74 23 00",
      mail: "",
      location: "Angers 49000",
      web: "https://www.concentrix.com",
    },
  },
};

export const profilData = {
  titleProfilData: ["Données du profil", "Profil Datas"],
  personalData: {
    title: ["Données Personnelles", "Personal Datas"],
    birth: ["Naissance", "Birth"],
    driverLicence: ["Permis de conduire", "Driver's licences"],
    city: ["Ville", "City"],
    phone: ["Tel", "Phone"],
    availability: ["Disponibilité", "Availability"],
    availabilityValue: [
      "‘Disponibilité immédiate’",
      "‘Immediate availability’",
    ],
  },
  skillData: {
    title: ["Données de Compétences", "Skills Datas"],
    usualUse: ["Courrament utilisé", "Usual Use"],
    notionsTest: ["‘Test unitaire(jest)", "‘Unit test(jest)’"],
    notionsAccess: ["‘Accessibilité’", "‘Accessibility’"],
    languages: ["Langues", "Languages"],
    languagesFr: ["Français: ", "French: "],
    languagesFrValue: ["‘Langue maternelle’", "‘Mother Tongue’"],
    languagesEn: ["Anglais: ", "English: "],
  },
  hobbiesData: {
    title: ["Données des Hobbies", "Hobbies Datas"],
    videoGame: ["Jeux vidéo", "Video games"],
    boardGame: ["Jeux de plateau", "Board games"],
    cultur: ["Culture", "Cultur"],
    movie: ["Films", "Movies"],
    music: ["Musique", "Music"],
  },
};
