export const portfolioData = {
  keyword: {
    skills: ["Compétences utilisées", "Skills used"],
    start: ["Lancer l'application: ", "Start the application: "],
    link: ["Liens vers le ", ["Link to the "]],
  },
  hrnet: {
    title: "Project n°7: HRnet",
    details: [
      "Ce projet est le dernier projet de mon parcours avec Openclassrooms. Il consistait à transformer une application web faite en full jQuery par une application en full react. De plus, l'une des consignes demandait de convertir l'un des modules en libairie NPM.",
      "This project is the last of my Javascript process. It consisted in transforming a web application made in full jQuery by an application in full react. In addition, one of the instructions asked to convert one of the modules into an NPM library.",
    ],
    skillsFr: [
      "Réalisation d'un design au choix",
      "Création d'une librairie NPM",
      "Utilisation de Material UI",
      "Utilisation de react-redux",
    ],
    skillsEn: [
      "Realization of a design of my choice",
      "Creation of an NPM library",
      "Using Material UI",
      "Using react-redux",
    ],
    startFr: [
      "Le project utilise npm comme gestionnaire de modules ainsi que NodeJs",
      "#1 - Installer NodeJs",
      "#2 - Installer npm",
      "#3 - Cloner ou télécharger le project de l'app",
      "#4 - Ouvrir le dossier d'app puis installer les dépendances requises avec npm install",
      "#5 - Lancer l'application avec npm start puis accepter de le démarrer sur http://localhost:3000",
    ],
    startEn: [
      "Project uses npm as package manager and NodeJs",
      "#1 - Install NodeJs",
      "#2 - Install npm",
      "#3 - Clone or Download the project APP",
      "#4 - Open App folder then install all dependencies required with npm install",
      "#5 - Start it with npm start and accept to start him on http://localhost:3000",
    ],
    picture: "hrnet",
    repo: "https://github.com/zKittyGB/HRnet",
    repoBack: "",
  },
  argentBank: {
    title: "Project n°6: ArgentBank",
    details: [
      "Ce projet est une application de gestion de connexion à des comptes banquais ainsi que de mise-à-jour des profils d'utilisateurs via une API.",
      "This project is a web application to loggin on your bank account and update user's profil via an API.",
    ],
    skillsFr: [
      "Utilisation de Fetch",
      "Gestion d'une API",
      "Utilisation de Redux Toolkit",
      "Mise-en-place de connexion sécurisé",
    ],
    skillsEn: [
      "Using Fetch",
      "Managing an API",
      "Using Redux Toolkit",
      "Setting up a secure connection",
    ],
    startFr: [
      "Le project utilise npm comme gestionnaire de modules ainsi que NodeJs",
      "#1 - Installer NodeJs",
      "#2 - Installer npm",
      "#3 - Cloner ou télécharger l'API côté backend",
      "#4 - Installer / démarrer MongoDB",
      "#5 - Suivre les instructions du readMe : https://github.com/zKittyGB/argentbank-api",
      "#6 - Cloner ou télécharger le project App",
      "#7 - Ouvrir le dossier de l'app puis installer les dépendances avec npm install ",
      "#8 - Lancer la avec npm start et accepter de la lancer en local",
    ],
    startEn: [
      "Project uses npm as package manager and NodeJs",
      "#1 - Install NodeJs",
      "#2 - Install npm",
      "#3 - Clone or Download the backend API",
      "#4 - Install / start MongoDb",
      "#5 - follow the ReadMe instructions in the readMe at : https://github.com/zKittyGB/argentbank-api",
      "#6 - Clone or Download the project APP",
      "#7 - Open App folder then install all dependencies required with npm install then launch it with npm strat and accept to start him on localhost",
    ],
    picture: "argentBank",
    repo: "https://github.com/zKittyGB/argentbank",
    repoBack: "https://github.com/zKittyGB/argentbank-api",
  },
  sportsee: {
    title: "Project n°5: Sportsee",
    details: [
      "Ce projet est une application web d'observation des performances physiques d'utilisateurs.",
      "This project is a web application to monitoring user's physicals performances.",
    ],
    skillsFr: [
      "Utilisation d'Axios",
      "Utilisation d'une API",
      "Utilisation de state local avec useState",
      "Utilisation de recharts react",
    ],
    skillsEn: [
      "Using Axios",
      "Using an API",
      "Using local State with useState",
      "Using recharts react",
    ],
    startFr: [
      "Le project utilise npm comme gestionnaire de modules ainsi que NodeJs",
      "#1 - Installer NodeJs",
      "#2 - Installer npm",
      "#3 - Cloner ou télécharger l'API côté backend",
      "#4 - Ouvrir le dossier de l'API puis installer les dépendances avec npm install. Ensuite, démarrer le avec npm start sur http://localhost:3000",
      "#5 - Cloner ou télécharger le projet APP",
      "#6 - Ouvrir le dossier de l'app, puis installer les dépendances de la même manière. Ensuite démarrer le avec npm start sur http://localhost:3001",
      "#7 - Par défaut, l'app démarrera sur l'utilisateur 12. Changer l'url par localhost:3001/12 ou localhost:3001/18 pour changer d'utilisateur",
    ],
    startEn: [
      "Project uses npm as package manager and NodeJs",
      "#1 - Install NodeJs",
      "#2 - Install npm",
      "#3 - Clone or Download the backend API",
      "#4 - Open API folder then install all dependencies required with npm install then launch it with npm start and let him start on http://localhost:3000",
      "#5 - Clone or Download the project APP",
      "#6 - Open App folder then install all dependencies required with npm install then launch it with npm strat and accept to start him on http://localhost:3001",
      "#7 - By default, the app will start on user 12. Change the url by localhost:3001/12 or localhost:3001/18 to switch between the two registered users",
    ],
    picture: "sportsee",
    repo: "https://github.com/zKittyGB/sportsee-front",
    repoBack: "https://github.com/zKittyGB/sportsee-back",
  },
  kasa: {
    title: "Project n°4: Kasa",
    details: [
      "Ce projet est une application web de réferencement immobilier. Il avait pour but la découverte de react.",
      "This project is a real estate referencement web application. Its purpose was to discover react.",
    ],
    skillsFr: [
      "Utilisation de state local avec useState",
      "Utilisation de react-router",
      "Première utilisation de react",
      "Utilisation de fetch",
      "Mise-en-place de rendu conditionnel",
    ],
    skillsEn: [
      "Using local State with useState",
      "Usinng react-router",
      "First use of react",
      "Using fetch",
      "Setting up conditional rendering",
    ],
    startFr: [
      "Le project utilise npm comme gestionnaire de modules ainsi que NodeJs",
      "#1 - Installer NodeJs",
      "#2 - Installer npm",
      "#3 - Cloner ou télécharger le projet APP",
      "#4 - Ouvrir le dossier de l'app, puis installer les dépendances de la même manière. Ensuite démarrer le avec npm start sur http://localhost:3000",
    ],
    startEn: [
      "Project uses npm as package manager and NodeJs",
      "#1 - Install NodeJs",
      "#2 - Install npm",
      "#3 - Clone or Download the backend API",
      "#4 - Open App folder then install all dependencies required with npm install then launch it with npm strat and accept to start him on http://localhost:3000",
    ],
    picture: "kasa",
    repo: "https://github.com/zKittyGB/kasa",
    repoBack: "",
  },
  ptitsplats: {
    title: "Project n°3: Les petits plats",
    details: [
      "Ce projet est une application web de recettes de cuisine. Le but était de créer système de moteur de recherche avec filtres.",
      "This project is a cooking recipes web application. Its purpose was to create a search engine system including filters possibility.",
    ],
    skillsFr: [
      "Utilisation de jQuery",
      "Création d'un moteur de recherche",
      "Création d'un système de filtre",
      "Utilisation de design patterns",
    ],
    skillsEn: [
      "Using jQuery",
      "Creation of a search engine",
      "Create a filter system",
      "Using design patterns",
    ],
    startFr: [
      "Le project utilise npm comme gestionnaire de modules ainsi que NodeJs",
      "#1 - Installer NodeJs",
      "#2 - Installer npm",
      "#3 - Cloner ou télécharger le projet APP",
      "#4 - Ouvrir le dossier de l'app, puis installer les dépendances de la même manière. Ensuite démarrer le avec l'option go live dans Vs Studio",
    ],
    startEn: [
      "Project uses npm as package manager and NodeJs",
      "#1 - Install NodeJs",
      "#2 - Install npm",
      "#3 - Clone or Download the backend API",
      "#4 - Open App folder then install all dependencies required with npm install then launch it with go live in Vs Studio.",
    ],
    picture: "ptitsplats",
    repo: "https://github.com/zKittyGB/les_petits_plats",
    repoBack: "",
  },
  fisheye: {
    title: "Project n°2: FishEye",
    details: [
      "Ce projet est une application web de référencement de photographes ainsi que de leurs portfolios via un système d'affichage dynamique.",
      "This projects is a referencement photographers web application and their portfolios via a dynamic display system.",
    ],
    skillsFr: [
      "Utilisation de jQuery",
      "Création d'un système d'affichage dynamique",
      "Création manuel d'un carrousel d'image",
      "Création d'un affichage par tri",
      "Création de modal",
      "Création de formulaire",
    ],
    skillsEn: [
      "Using jQuery",
      "Creation of a dynamic display system",
      "Manual creation of a slide show picture",
      "Creating a display by sort",
      "Creating modal",
      "Creating form",
    ],
    startFr: [
      "Le project utilise npm comme gestionnaire de modules ainsi que NodeJs",
      "#1 - Installer NodeJs",
      "#2 - Installer npm",
      "#3 - Cloner ou télécharger le projet APP",
      "#4 - Ouvrir le dossier de l'app, puis installer les dépendances de la même manière. Ensuite démarrer le avec l'option go live dans Vs Studio",
    ],
    startEn: [
      "Project uses npm as package manager and NodeJs",
      "#1 - Install NodeJs",
      "#2 - Install npm",
      "#3 - Clone or Download the backend API",
      "#4 - Open App folder then install all dependencies required with npm install then launch it with go live in Vs Studio.",
    ],
    picture: "fisheye",
    repo: "https://github.com/zKittyGB/Front-End-Fisheye",
    repoBack: "",
  },
  ohmyfood: {
    title: "Project n°1: Ohmyfood",
    details: [
      "Ce projet est un site internet référençant les recettes de cuisines de différents restaurants gastronomiques. Il avait pour but de nous faire découvrir le système d'animation en CSS ainsi que le fait de reproduire une maquette.",
      "This project is a gourmet cooking recipes referencement of differents gourmets restaurants. Its purpose was to introduce us to the css animations system and reproducing a model.",
    ],
    skillsFr: ["Reproduire une maquette", "Création d'animation css"],
    skillsEn: ["Reproduce a model", "Creating css animations"],
    startFr: [
      "#1 - Cloner ou télécharger le projet App",
      "#2 - Ouvrir le dossier de l'app, puis démarrer le avec l'option go live dans Vs Studio",
    ],
    startEn: [
      "#1 - Clone or Download the App",
      "#2 - Open App folder then launch it with go live in Vs Studio.",
    ],
    picture: "ohmyfood",
    repo: "https://github.com/zKittyGB/ohmyfood",
    repoBack: "",
  },
};
